[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
# if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
if = 'has("nvim")'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000

  inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<TAB>" :
  \ deoplete#mappings#manual_complete()

  function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~ '\s'
  endfunction"}}}
'''

[[plugins]]
repo = 'w0rp/ale'
on_i = 1
hook_add = """
  let g:ale_set_loclist = 1
  let g:ale_set_quickfix = 0
  let g:ale_open_list = 1
  let g:ale_linters = {
    \ 'haskell': ['hlint', 'stack-ghc-mod'],
    \ 'rust': ['cargo',],
    \ 'elixir': ['credo']
  \}
  nmap <silent> <C-n> <Plug>(ale_next_wrap)
  nmap <silent> <C-n> <Plug>(ale_previous_wrap)
"""

[[plugins]]
repo = 'kassio/neoterm'
if = 'has("nvim")'
hook_add = '''
  set sh=bash
  let g:neoterm_position = 'vertical'
'''

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

# [[plugins]]
# repo = 'kristijanhusak/vim-hybrid-material'
#
# [[plugins]]
# repo = 'tomasr/molokai'
#
# [[plugins]]
# repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  let g:gruvbox_contrast_dark = 'medium'
'''

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = '''
  let g:seiya_target_groups = has('nvim') ? ['guibg'] : ['ctermbg']
  let g:seiya_auto_enable = 1
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['tpope/vim-fugitive']
hook_add = '''
let g:lightline = {
  \ 'colorscheme' : 'gruvbox',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'fugitive', 'filename' ] ]
  \ },
  \ 'separator': { 'left': '', 'right': ' ' },
  \ 'subseparator': { 'left': '', 'right': ' ' },
  \ 'component_function': {
  \   'fugitive': 'LightlineFugitive',
  \   'readonly': 'LightlineReadonly',
  \   'modified': 'LightlineModified',
  \   'filename': 'LightlineFilename',
  \ },
  \ }

function! LightlineModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! LightlineReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return ""
  else
    return ""
  endif
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
       \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
       \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction

function! LightlineFugitive()
  if exists("*fugitive#head")
    let branch = fugitive#head()
    return branch !=# '' ? ' ' .branch : ''
  endif
  return ''
endfunction
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = [ 'cpsm' ]
hook_post_source = '''
  " ripgrep on file_rec source
  " call denite#custom#var('file_rec', 'command',
  "    \ ['rg', '--files', '--glob', '!.git', ''])
  " the_silver_searcher
  call denite#custom#var('file_rec', 'command',
      \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  
  " Ripgrep command on grep source
  call denite#custom#var('grep', 'command', ['rg'])
  call denite#custom#var('grep', 'default_opts',
      \ ['--vimgrep', '--no-heading', '--follow'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  call denite#custom#source('file_rec', 'matchers', ['matcher_cpsm'])
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''
