"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$hostname$directory$git_branch$git_status$fill
$os$shell$character[>](bold cyan) """

right_format = """$cmd_duration"""

continuation_prompt = '[>>](bold cyan) '

add_newline = false

[fill]
symbol = '-'
style = 'bold green'

[character]
success_symbol = '\[[➜](bold green)\]'
error_symbol = '\[[✗](bold red)\]'
vimcmd_symbol = '\[[V](bold green)\]'

[directory]
format = '\[[$path]($style)[$read_only]($read_only_style)\] '

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[os]
format = "[($type )]($style)"
#format = "$symbol[($type )]($style)"
style = "bold blue"
disabled = false

#[os.symbols]
#Windows = " "
#Arch = "Arch "
#Ubuntu = "Ubuntu "

[shell]
zsh_indicator = 'zsh'
bash_indicator = 'bash'
powershell_indicator = 'pwsh'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false
