#!/bin/bash

sxhkd &
#albert &
xautolock -locker "systemctl suspend" -time 5 -detectsleep &
export _JAVA_AWT_WM_NONREPARENTING=1

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI2 -d HDMI
#bspc desktop 1 -l monocle
bspc config border_width 2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true
bspc config honor_size_hints false
bspc rule -a Wine state=floating
bspc rule -a mpv state=floating
bspc rule -a qjackctl state=floating
bspc rule -a albert focus=on
bspc rule -a scratch state=floating
bspc rule -a llpp state=pseudo_tiled
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv state=floating
bspc rule -a MComix state=fullscreen
bspc rule -a Google-chrome desktop=1 follow=on
bspc rule -a Firefox desktop=1 follow=on
bspc rule -a Thunderbird desktop=1 follow=on
bspc rule -a Tilix desktop=2 follow=on
bspc rule -a Emacs desktop=3 follow=on state=tiled
bspc rule -a nvim-qt state=fullscreen
bspc rule -a ncmpcpp state=floating flag sticky=on
bspc rule -a calibre:calibre-ebook-viewer state=floating
$HOME/.config/polybar/launch.sh bspwm
